# Generated by Django 3.0.3 on 2020-02-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=25)),
                ('color_domain_one', models.CharField(max_length=25)),
                ('color_domain_two', models.CharField(max_length=25)),
                ('color_accent_one', models.CharField(max_length=25)),
                ('color_accent_two', models.CharField(max_length=25)),
                ('status', models.IntegerField(choices=[(0, 'Private'), (1, 'Publish')], default=0)),
            ],
            options={
                'ordering': ['color_name'],
            },
        ),
    ]
